version: 2.1

jobs:
  ejecutar-tests-postman:
    docker:
      - image: postman/collection-runner:latest
    steps:
      - checkout
      - run:
          name: Clonar repositorio
          command: git clone https://github.com/jmurilt0413/TestNewman
      - run:
          name: Navegar al directorio de tests
          command: test_postman
      - run:
          name: Ejecutar tests de Postman
          command: npx postman collection run Integration Testing.postman_collection.json  --report --report-type json
      - run:
          name: Generar reporte HTML
          command: npx postman collection run Testing  --report --report-type html

workflows:
  ejecutar-tests-postman-test: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - ejecutar-tests-postman