# Use la última versión 2.1 del motor de proceso de la canalización de CircleCI.
# Consulte: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  say-hello:
    # Especifique el entorno de ejecución. Puede especificar una imagen de Docker Hub o usar una de nuestras imágenes de conveniencia del Developer Hub de CircleCI.
    # Consulte: https://circleci.com/docs/executor-intro/ y https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Especifique la versión que desee aquí
      # Consulte: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current

    # Agregue pasos al trabajo
    # Consulte: https://circleci.com/docs/jobs-steps/#steps-overview y https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout el código como primer paso.
      - checkout
      - run:
          name: Instalar Node.js y npm
          command: |
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
            npm --version
            node --version
            mkdir ~/.npm-global
            npm config set prefix '~/.npm-global'
            export PATH=~/.npm-global/bin:$PATH
            source ~/.bashrc
            npm install -g newman
            npm install -g newman-reporter-html
            newman --version
            export PATH_NEWMAN=~/.npm-global/bin/newman:PATH_NEWMAN
            source ~/.bashrc
            git clone https://github.com/jmurilt0413/TestNewman
            cd TestNewman/test_postman
            newman run Integration_Testing.postman_collection.json --reporters html --reporter-html-export report.html

# Orquestar trabajos usando flujos de trabajo
# Consulte: https://circleci.com/docs/workflows/ y https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow: # Este es el nombre del flujo de trabajo, siéntase libre de cambiarlo para que coincida mejor con su flujo de trabajo.
    # Dentro del flujo de trabajo, define los trabajos que desea ejecutar.
    jobs:
      - say-hello
