# Use la última versión 2.1 del motor de proceso de la canalización de CircleCI.
# Consulte: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  say-hello:
    # Especifique el entorno de ejecución. Puede especificar una imagen de Docker Hub o usar una de nuestras imágenes de conveniencia del Developer Hub de CircleCI.
    # Consulte: https://circleci.com/docs/executor-intro/ y https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Especifique la versión que desee aquí
      # Consulte: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current

    # Agregue pasos al trabajo
    # Consulte: https://circleci.com/docs/jobs-steps/#steps-overview y https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout el código como primer paso.
      - checkout
      - run:
          name: Instalar Node.js y npm
          command: |
            curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
            npm --version
            node --version
            npm install -g newman
      - run:
          name: Clonar repositorio
          command: git clone https://github.com/jmurilt0413/TestNewman
      - run:
          name: Navegar al directorio de tests
          command: cd TestNewman
      - run:
          name: Ejecutar tests de Postman
          command: newman run Integration\ Testing.postman_collection.json --reporters junit,json --reporter-junit-export report.xml --reporter-json-export report.json
      - run:
          name: Generar reporte HTML
          command: newman run Integration\ Testing.postman_collection.json --reporters html --reporter-html-export report.html

# Orquestar trabajos usando flujos de trabajo
# Consulte: https://circleci.com/docs/workflows/ y https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow: # Este es el nombre del flujo de trabajo, siéntase libre de cambiarlo para que coincida mejor con su flujo de trabajo.
    # Dentro del flujo de trabajo, define los trabajos que desea ejecutar.
    jobs:
      - say-hello
